# Generated by Django 2.0.7 on 2018-07-06 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20180706_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
