# Generated by Django 2.0.7 on 2018-07-09 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmessage',
            name='receiver_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='message_receiver_user_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbackmessage',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_sender_user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
