# Generated by Django 2.0.7 on 2018-07-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180706_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackMessages',
            new_name='FeedbackMessage',
        ),
    ]
