# Generated by Django 2.0.7 on 2018-07-06 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20180706_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmessage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
