# Generated by Django 2.0.7 on 2018-07-07 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0006_auto_20180706_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmessage',
            name='sender_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
