# Generated by Django 2.0.7 on 2018-07-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20180708_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='video_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
