# Generated by Django 2.0.7 on 2018-07-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20180714_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='cover_image',
            new_name='banner_ad_image',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='thumbnail',
            new_name='interstitial_image',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='view_hits',
        ),
    ]
