# Generated by Django 2.0.7 on 2018-07-14 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20180714_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementuserpreference',
            name='pref_id',
        ),
        migrations.RemoveField(
            model_name='advertisementuserpreference',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='advertisementcriteria',
            name='ad_id',
        ),
        migrations.RemoveField(
            model_name='advertisementcriteria',
            name='pref_id',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='criteria',
            field=models.ManyToManyField(blank=True, to='ads.AdvertisementCriteria'),
        ),
        migrations.AddField(
            model_name='advertisementcriteria',
            name='criteria',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdvertisementPreferenceCriteria',
        ),
        migrations.DeleteModel(
            name='AdvertisementUserPreference',
        ),
    ]
