# Generated by Django 2.0.7 on 2018-07-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180714_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='disabilities',
            field=models.ManyToManyField(blank=True, null=True, to='users.Disabilities'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
