# Generated by Django 2.0.7 on 2018-07-14 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180714_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gender',
            new_name='gender_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='nationality',
            new_name='nationality_id',
        ),
    ]
