# Generated by Django 2.0.7 on 2018-07-04 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feeds.Type'),
        ),
    ]
