# Generated by Django 2.0.7 on 2018-07-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='is_starred',
        ),
    ]
