# Generated by Django 2.0.7 on 2018-07-04 18:21

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('feeds', '0002_auto_20180704_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='FeedType',
        ),
    ]
