# Generated by Django 2.0.7 on 2018-07-10 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_remove_feed_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtype',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
