# Generated by Django 2.0.7 on 2018-07-05 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20180704_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedtype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
