# Generated by Django 2.0.7 on 2018-07-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20180710_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='posted_date',
            new_name='date_posted',
        ),
    ]
