# Generated by Django 2.0.7 on 2018-07-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20180705_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
